#!/usr/bin/env node
'use strict';

/*
 * DEP-AC-05: does src/vault/publishset.js's computePublishedSet() predict
 * exactly the HTML the pinned generator's real build() writes? Builds the
 * given vault with Scriptorium's own atomic-build pipeline (the same code
 * path `scriptorium build --force` uses), then compares the built tree
 * against computePublishedSet()'s own published-page list.
 *
 * The pin writes some pages that have no single vault-source page behind
 * them (the landing page, the 404, the timeline, the story index and its
 * per-unit pages, and each section's own index.html) — those are
 * subtracted from the built tree before comparing, not added to the
 * expected side, so a real drift in computePublishedSet's own per-page
 * predictions can never hide behind them.
 *
 * This is a `scripts/` tool, not `src/`: like scripts/generator-pin.js and
 * scripts/package.js, it reaches into node_modules/gm-apprentice-publish
 * directly for read-only introspection (DIR_LABELS, to know the generated
 * section-index set). Structural decision 1's "the ONLY Scriptorium module
 * that requires generator internals" is about src/generator/pinned.js
 * being the sole PRODUCT-code chokepoint; build/dev tooling under scripts/
 * already has this exception (the pin verifier hashes the installed tree
 * directly; the packager reads pkg.assets against it).
 */

const fs = require('fs');
const path = require('path');

function defaultDirLabels() {
  // eslint-disable-next-line global-require
  return require('gm-apprentice-publish/lib/templates/base').DIR_LABELS;
}

/** Every *.html file under dir, as a POSIX path relative to dir. */
function walkHtmlFiles(dir) {
  const out = [];
  (function walk(abs, rel) {
    for (const entry of fs.readdirSync(abs, { withFileTypes: true })) {
      const entryAbs = path.join(abs, entry.name);
      const entryRel = rel ? `${rel}/${entry.name}` : entry.name;
      if (entry.isDirectory()) {
        walk(entryAbs, entryRel);
      } else if (entry.name.endsWith('.html')) {
        out.push(entryRel);
      }
    }
  })(dir, '');
  return out;
}

/**
 * True for an output HTML file that is generated by the build itself
 * rather than being one vault page's own output: index.html, 404.html,
 * timeline.html, story.html, every story/** page, and each DIR_LABELS
 * section's own <dir>/index.html.
 */
function isGeneratedExtra(relPath, dirLabels) {
  if (relPath === 'index.html' || relPath === '404.html' || relPath === 'timeline.html' || relPath === 'story.html') {
    return true;
  }
  if (relPath === 'story' || relPath.startsWith('story/')) return true;
  for (const dir of Object.keys(dirLabels)) {
    if (relPath === `${dir}/index.html`) return true;
  }
  return false;
}

/**
 * @param {string} outDir absolute path to a real build's output directory
 * @param {object} publishSet computePublishedSet()'s return value
 * @param {{dirLabels?: object}} [opts]
 * @returns {{ ok: boolean, missing: string[], extra: string[], expected: string[], actual: string[] }}
 *   missing: predicted to publish but absent from the built tree.
 *   extra: built, but not predicted (after subtracting the generated set).
 */
function compareBuiltToPublishSet(outDir, publishSet, opts = {}) {
  const dirLabels = opts.dirLabels || defaultDirLabels();
  const actual = new Set(walkHtmlFiles(outDir).filter((p) => !isGeneratedExtra(p, dirLabels)));

  const expected = new Set(
    publishSet.publishedPages
      .filter((p) => p.frontmatter.type !== 'world_flags' && p.outputPath)
      .map((p) => p.outputPath),
  );

  const missing = [...expected].filter((p) => !actual.has(p)).sort();
  const extra = [...actual].filter((p) => !expected.has(p)).sort();

  return {
    ok: missing.length === 0 && extra.length === 0,
    missing,
    extra,
    expected: [...expected].sort(),
    actual: [...actual].sort(),
  };
}

function parseArgs(argv) {
  const out = {};
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a.startsWith('--')) {
      const key = a.slice(2);
      const next = argv[i + 1];
      if (next === undefined || next.startsWith('--')) {
        out[key] = true;
      } else {
        out[key] = next;
        i++;
      }
    }
  }
  return out;
}

function runCli() {
  const args = parseArgs(process.argv.slice(2));
  if (!args.vault || !args['site-config'] || !args.out) {
    console.error('usage: equivalence-check.js --vault <dir> --site-config <vault.config.json> --out <scratch-out-dir>');
    process.exitCode = 1;
    return;
  }

  const vaultPath = path.resolve(args.vault);
  const siteConfigPath = path.resolve(args['site-config']);
  const finalOut = path.resolve(args.out);
  const siteDir = path.dirname(siteConfigPath);
  const userJsonConfig = JSON.parse(fs.readFileSync(siteConfigPath, 'utf8'));

  // eslint-disable-next-line global-require
  const { runAtomicBuild } = require('../src/build/run');
  // eslint-disable-next-line global-require
  const { computePublishedSet } = require('../src/vault/publishset');

  // Track D2, Structural decision 5: this tool deliberately builds vaults that
  // may carry withheld-name leaks (it is checking published-page prediction,
  // not leak-cleanliness), so `force: true` overrides the pre-swap
  // output-leak scan rather than being refused by it. Every overridden
  // finding is printed below so the override is never silent.
  const buildResult = runAtomicBuild({
    vaultPath,
    userJsonConfig,
    finalOut,
    siteDir,
    campaign: 'equivalence-check',
    force: true,
  });
  if (buildResult.refusedByScan) {
    // force: true means this should never happen; kept as a defensive
    // report rather than an assertion, since a future scan bug should be
    // loud here too.
    console.error('equivalence-check: unexpected refusedByScan with force: true');
    process.exitCode = 1;
    return;
  }
  if (!buildResult.ok) {
    console.error('equivalence-check: the real build itself failed:');
    console.error(buildResult.error && buildResult.error.message);
    for (const e of buildResult.renderErrors || []) console.error(`  - ${e.kind} ${e.outputPath || ''}: ${e.message}`);
    process.exitCode = 1;
    return;
  }
  if (buildResult.outputScan && buildResult.outputScan.overridden) {
    console.log(`equivalence-check: --force overrode ${buildResult.outputScan.findings.length} output-leak scan finding(s):`);
    for (const f of buildResult.outputScan.findings) {
      console.log(`  OVERRIDDEN ${f.id} ${f.outputPath || f.path || ''} ${f.message}`);
    }
  }

  const jsonConfigForPublishSet = { ...userJsonConfig, vaultPath };
  const publishSet = computePublishedSet(vaultPath, jsonConfigForPublishSet);
  const result = compareBuiltToPublishSet(finalOut, publishSet);

  if (result.ok) {
    console.log(`equivalence-check: OK, ${result.expected.length} published page(s) match the built tree exactly`);
    process.exitCode = 0;
    return;
  }

  console.error('equivalence-check: MISMATCH');
  if (result.missing.length > 0) {
    console.error(`  predicted but not built (${result.missing.length}):`);
    for (const p of result.missing) console.error(`    - ${p}`);
  }
  if (result.extra.length > 0) {
    console.error(`  built but not predicted (${result.extra.length}):`);
    for (const p of result.extra) console.error(`    - ${p}`);
  }
  process.exitCode = 1;
}

if (require.main === module) {
  runCli();
}

module.exports = { compareBuiltToPublishSet, walkHtmlFiles, isGeneratedExtra };
